<<<<<<< Updated upstream
# Generated by Django 5.1.4 on 2025-02-25 14:50
=======
# Generated by Django 5.1.4 on 2025-02-20 12:33
>>>>>>> Stashed changes

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAppointmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Follow-up', 'Follow-up'), ('Routine Checkup', 'Routine Checkup'), ('Emergency Visit', 'Emergency Visit'), ('Prescription Refill', 'Prescription Refill')], max_length=50, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LabTechnicianAppointmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test_type', models.CharField(choices=[('Complete Blood Count (CBC)', 'Complete Blood Count (CBC)'), ('Basic Metabolic Panel (BMP)', 'Basic Metabolic Panel (BMP)'), ('Hemoglobin A1c (HbA1c)', 'Hemoglobin A1c (HbA1c)'), ('Testosterone Test', 'Testosterone Test'), ('PCR Test', 'PCR Test'), ('BRCA Gene Test', 'BRCA Gene Test')], max_length=50, unique=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.appointment')),
                ('appointment_type', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('follow_up', models.BooleanField(default=False)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            bases=('appointments.appointment',),
        ),
        migrations.CreateModel(
            name='TechnicianAppointment',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.appointment')),
<<<<<<< Updated upstream
                ('lab_test_type', models.CharField(max_length=100)),
                ('test_status', models.CharField(blank=True, default='Pending', max_length=50, null=True)),
                ('results_available', models.BooleanField(blank=True, default=False, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
=======
                ('lab_test_id', models.IntegerField()),
                ('test_type', models.CharField(max_length=100)),
                ('test_status', models.CharField(default='Pending', max_length=50)),
                ('results_available', models.BooleanField(default=False)),
>>>>>>> Stashed changes
            ],
            bases=('appointments.appointment',),
        ),
    ]
