# Generated by Django 5.1.4 on 2025-02-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('ehr', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default='patient', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='appointment',
            field=models.ForeignKey(default='appointment', on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='appointments.doctorappointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='doctor',
            field=models.ForeignKey(default='doctor', on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='users.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clinicadmin'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='doctor',
            field=models.ForeignKey(default='doctor', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='users.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='ehr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_appointment_ehr', to='ehr.ehr'),
        ),
        migrations.AddField(
            model_name='technicianappointment',
            name='ehr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_appointment_ehr', to='ehr.ehr'),
        ),
        migrations.AddField(
            model_name='technicianappointment',
            name='lab_technician',
            field=models.ForeignKey(default='labtech', on_delete=django.db.models.deletion.CASCADE, related_name='technician_appointments', to='users.labtechnician'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled'), ('Checked-In', 'Checked-In'), ('No-Show', 'No-Show')], default='Scheduled', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cancellationrequest',
            constraint=models.UniqueConstraint(fields=('appointment',), name='unique_cancellation_request_per_appointment'),
        ),
    ]
