# Generated by Django 5.1.4 on 2025-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='consultation_fee',
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='fee',
            field=models.JSONField(default=dict),
        ),
    ]
