# Generated by Django 5.1.4 on 2025-02-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnicianappointmentfee',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianappointmentfee',
            name='lab_test_type',
            field=models.CharField(choices=[('Complete Blood Count (CBC)', 'Complete Blood Count (CBC)'), ('Basic Metabolic Panel (BMP)', 'Basic Metabolic Panel (BMP)'), ('Hemoglobin A1c (HbA1c)', 'Hemoglobin A1c (HbA1c)'), ('Testosterone Test', 'Testosterone Test'), ('PCR Test', 'PCR Test'), ('BRCA Gene Test', 'BRCA Gene Test')], default='Complete Blood Count (CBC)', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
