<<<<<<< Updated upstream
# Generated by Django 5.1.4 on 2025-02-25 14:50
=======
# Generated by Django 5.1.4 on 2025-02-20 12:33
>>>>>>> Stashed changes

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
<<<<<<< Updated upstream
=======
        ('ehr', '0001_initial'),
>>>>>>> Stashed changes
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient'),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clinicadmin'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='users.doctor'),
        ),
        migrations.AddField(
<<<<<<< Updated upstream
=======
            model_name='doctorappointment',
            name='ehr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_appointment_ehr', to='ehr.ehr'),
        ),
        migrations.AddField(
>>>>>>> Stashed changes
            model_name='cancellationrequest',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='appointments.doctorappointment'),
        ),
        migrations.AddField(
            model_name='technicianappointment',
<<<<<<< Updated upstream
=======
            name='ehr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_appointment_ehr', to='ehr.ehr'),
        ),
        migrations.AddField(
            model_name='technicianappointment',
>>>>>>> Stashed changes
            name='lab_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_appointments', to='users.labtechnician'),
        ),
        migrations.AddConstraint(
            model_name='cancellationrequest',
            constraint=models.UniqueConstraint(fields=('appointment',), name='unique_cancellation_request_per_appointment'),
        ),
    ]
