# Generated by Django 5.1.4 on 2025-03-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='recommended_tests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
