# Generated by Django 5.1.4 on 2025-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_labtechnicianappointmentfee_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianappointment',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='technicianappointment',
            name='lab_test_type',
            field=models.CharField(default='Complete Blood Count (CBC)', max_length=50),
            preserve_default=False,
        ),
    ]
