# Generated by Django 5.1.4 on 2025-02-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_technicianappointment_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianappointment',
            name='test_type',
        ),
    ]
