# Generated by Django 5.1.4 on 2025-02-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctorappointmentfee_alter_doctorappointment_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnicianAppointmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='doctorappointmentfee',
            name='appointment_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Follow-up', 'Follow-up'), ('Routine Checkup', 'Routine Checkup'), ('Emergency Visit', 'Emergency Visit'), ('Prescription Refill', 'Prescription Refill')], max_length=50, unique=True),
        ),
    ]
