# Generated by Django 5.1.4 on 2025-03-11 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_availability'),
        ('users', '0002_remove_patient_medical_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='completion_time',
            new_name='end_time',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.doctor')),
            ],
        ),
    ]
