# Generated by Django 5.1.4 on 2025-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_technicianappointment_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianappointment',
            name='lab_test_type',
            field=models.CharField(max_length=100),
        ),
    ]
