# Generated by Django 5.1.4 on 2025-02-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_labtechnicianappointmentfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Follow-up', 'Follow-up'), ('Routine Checkup', 'Routine Checkup'), ('Emergency Visit', 'Emergency Visit'), ('Prescription Refill', 'Prescription Refill')], max_length=50),
        ),
    ]
