# Generated by Django 5.1.4 on 2025-02-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_doctorappointment_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_type',
            field=models.CharField(max_length=50),
        ),
    ]
