# Generated by Django 5.1.4 on 2025-03-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_time_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
