# Generated by Django 5.1.4 on 2025-02-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_cancellationrequest'),
        ('users', '0011_alter_clinicadmin_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cancellationrequest',
            constraint=models.UniqueConstraint(fields=('appointment',), name='unique_cancellation_request_per_appointment'),
        ),
    ]
