# Generated by Django 5.1.4 on 2025-03-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
