# Generated by Django 5.1.4 on 2025-03-14 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_check_in_time_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
