# Generated by Django 5.1.4 on 2025-03-14 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_appointment_appointment_date_and_more'),
        ('users', '0002_remove_patient_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='lab_technician',
            field=models.ForeignKey(default='LT001', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.labtechnician'),
            preserve_default=False,
        ),
    ]
