# Generated by Django 5.1.4 on 2025-03-14 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_timeslot_lab_technician'),
        ('users', '0002_remove_patient_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='lab_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.labtechnician'),
        ),
    ]
