# Generated by Django 5.1.4 on 2025-03-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_timeslot_doctor_alter_timeslot_lab_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='specialization',
        ),
    ]
