# Generated by Django 5.1.4 on 2025-03-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_appointment_time_slot_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_time_slot',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.timeslot'),
        ),
    ]
