# Generated by Django 5.1.4 on 2025-03-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_remove_appointment_appointment_datetime_and_more'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianappointment',
            name='lab_test_type',
        ),
        migrations.RemoveField(
            model_name='technicianappointment',
            name='results_available',
        ),
        migrations.RemoveField(
            model_name='technicianappointment',
            name='test_status',
        ),
        migrations.AddField(
            model_name='technicianappointment',
            name='lab_tests',
            field=models.ManyToManyField(related_name='appointments', to='labs.labtesttype'),
        ),
    ]
