# Generated by Django 5.1.4 on 2025-03-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_remove_technicianappointment_lab_test_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabTechnicianAppointmentFee',
        ),
    ]
