# Generated by Django 5.1.4 on 2025-03-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_remove_technicianappointment_lab_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='checkout_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='checkin_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checkout_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
