# Generated by Django 5.1.4 on 2025-04-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_remove_doctorappointment_recommended_tests'),
        ('users', '0003_alter_labtechnician_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_cancellation_requests', to='appointments.technicianappointment')),
                ('lab_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_cancellation_requests', to='users.labtechnician')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.labadmin')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appointment',), name='unique_technician_cancellation_request_per_appointment')],
            },
        ),
    ]
