# Generated by Django 5.1.4 on 2025-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CBC', 'Complete Blood Count (CBC)'), ('BloodSugar', 'Blood Sugar Test'), ('HbA1c', 'HbA1c (Diabetes Test)'), ('LipidProfile', 'Lipid Profile (Cholesterol Test)'), ('Thyroid', 'Thyroid Function Test (T3, T4, TSH)'), ('UrineTest', 'Urine Analysis'), ('LiverFunction', 'Liver Function Test (LFT)'), ('KidneyFunction', 'Kidney Function Test (KFT)'), ('Electrolytes', 'Electrolyte Panel'), ('CRP', 'C-Reactive Protein (CRP) Test'), ('VitaminD', 'Vitamin D Test'), ('VitaminB12', 'Vitamin B12 Test'), ('IronPanel', 'Iron Panel (Ferritin, TIBC)'), ('GeneticTest', 'Genetic Testing'), ('Other', 'Other')], max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Blood Test', 'Blood Test'), ('Imaging', 'Imaging'), ('Biopsy', 'Biopsy'), ('Urine Test', 'Urine Test'), ('Genetic Test', 'Genetic Test'), ('Other', 'Other')], default='Other', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
