# Generated by Django 5.1.4 on 2025-03-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
        ('users', '0002_remove_patient_medical_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('results_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.labtechnician')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='labs.labtesttype')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_details', models.TextField()),
                ('reference_range', models.TextField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.labtechnician')),
                ('test_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='labs.labtestorder')),
            ],
        ),
    ]
