# Generated by Django 5.1.4 on 2025-03-19 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_remove_technicianappointment_lab_tests'),
        ('labs', '0002_labtestorder_labtestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestorder',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='appointments.technicianappointment'),
            preserve_default=False,
        ),
    ]
