# Generated by Django 5.1.4 on 2025-03-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_labtestorder_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtestorder',
            old_name='appointment',
            new_name='lab_technician_appointment',
        ),
        migrations.RemoveField(
            model_name='labtestorder',
            name='assigned_technician',
        ),
    ]
