# Generated by Django 5.1.4 on 2025-03-19 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_rename_appointment_labtestorder_lab_technician_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestorder',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='labs.labtesttype'),
        ),
    ]
