# Generated by Django 5.1.4 on 2025-03-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_alter_labtestorder_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestorder',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='labs.labtesttype'),
        ),
    ]
