# Generated by Django 5.1.4 on 2025-03-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_alter_labtestorder_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestorder',
            name='test_type',
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='test_types',
            field=models.ManyToManyField(related_name='test_orders', to='labs.labtesttype'),
        ),
    ]
