# Generated by Django 5.1.4 on 2025-03-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_remove_labtestorder_test_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestorder',
            name='updated_at',
        ),
    ]
