# Generated by Django 5.1.4 on 2025-03-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_rename_reference_range_labtestresult_text_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labtestorder',
            name='test_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Collected', 'Collected'), ('Pending Entry', 'Pending Entry'), ('Pending Finalization', 'Pending Finalization'), ('Finalized', 'Finalized'), ('Requires Re-entry', 'Requires Re-entry'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtesttype',
            name='category',
            field=models.CharField(choices=[('Blood Test', 'Blood Test'), ('Imaging Test', 'Imaging Test'), ('Pathology Report', 'Pathology Report'), ('Urine Test', 'Urine Test')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='labtesttype',
            name='name',
            field=models.CharField(choices=[('CBC', 'Complete Blood Count (CBC)'), ('BloodSugar', 'Blood Sugar Test'), ('HbA1c', 'HbA1c (Diabetes Test)'), ('LipidProfile', 'Lipid Profile (Cholesterol Test)'), ('Thyroid', 'Thyroid Function Test (T3, T4, TSH)'), ('LiverFunction', 'Liver Function Test (LFT)'), ('KidneyFunction', 'Kidney Function Test (KFT)'), ('Electrolytes', 'Electrolyte Panel'), ('CRP', 'C-Reactive Protein (CRP) Test'), ('VitaminD', 'Vitamin D Test'), ('VitaminB12', 'Vitamin B12 Test'), ('IronPanel', 'Iron Panel (Ferritin, TIBC)'), ('UrineTest', 'Urine Analysis'), ('XRay', 'X-Ray'), ('MRI', 'Magnetic Resonance Imaging (MRI)'), ('CTScan', 'Computed Tomography (CT) Scan'), ('Ultrasound', 'Ultrasound'), ('Biopsy', 'Biopsy'), ('Histopathology', 'Histopathology')], max_length=100, unique=True),
        ),
    ]
