# Generated by Django 5.1.4 on 2025-03-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_labtestorder_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestorder',
            name='test_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
