# Generated by Django 5.1.4 on 2025-03-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0011_alter_labtestorder_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestorder',
            name='test_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
