# Generated by Django 5.1.4 on 2025-03-28 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0013_rename_text_results_labtestresult_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresult',
            name='test_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='labs.labtesttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='test_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='labs.labtestorder'),
        ),
    ]
