# Generated by Django 5.1.4 on 2025-03-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0015_labtestresult_result_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestorder',
            name='test_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Review Required', 'Review Required'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
