# Generated by Django 5.1.4 on 2025-03-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0016_alter_labtestorder_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresult',
            name='admin_comments',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
