# Generated by Django 5.1.4 on 2025-03-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0017_labtestresult_admin_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestresult',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
