# Generated by Django 5.1.4 on 2025-02-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EHR',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_conditions', models.JSONField(blank=True, null=True)),
                ('current_medications', models.JSONField(blank=True, null=True)),
                ('immunization_records', models.JSONField(blank=True, null=True)),
                ('nail_image_analysis', models.JSONField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('diagnoses', models.JSONField(blank=True, default={'diagnoses': ['art', 'necessary']}, null=True)),
                ('visit_date', models.DateField()),
                ('category', models.CharField(choices=[('Chronic', 'Chronic'), ('Emergency', 'Emergency'), ('Preventive', 'Preventive'), ('General', 'General')], default='General', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('consulted_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
