<<<<<<< HEAD
<<<<<<< Updated upstream
# Generated by Django 5.1.4 on 2025-02-25 14:50
=======
# Generated by Django 5.1.4 on 2025-02-20 12:33
>>>>>>> Stashed changes
=======
# Generated by Django 5.1.4 on 2025-02-20 12:33
>>>>>>> d763ff1f7562f45b0396423f2d6f887a01b25337

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_conditions', models.JSONField(blank=True, null=True)),
                ('current_medications', models.JSONField(blank=True, null=True)),
                ('immunization_records', models.JSONField(blank=True, null=True)),
                ('nail_image_analysis', models.JSONField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('diagnoses', models.JSONField(blank=True, null=True)),
                ('recommended_lab_test', models.JSONField(blank=True, default=list, null=True)),
                ('visit_date', models.DateField()),
                ('category', models.CharField(choices=[('Chronic', 'Chronic'), ('Emergency', 'Emergency'), ('Preventive', 'Preventive'), ('General', 'General')], default='General', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
<<<<<<< Updated upstream
                ('comments', models.TextField(blank=True, null=True)),
=======
                ('consulted_by', models.CharField(blank=True, max_length=255)),
>>>>>>> Stashed changes
=======
                ('consulted_by', models.CharField(blank=True, max_length=255)),
>>>>>>> d763ff1f7562f45b0396423f2d6f887a01b25337
            ],
        ),
    ]
