<<<<<<< HEAD
<<<<<<< Updated upstream
# Generated by Django 5.1.4 on 2025-02-25 14:50
=======
# Generated by Django 5.1.4 on 2025-02-20 12:33
>>>>>>> Stashed changes
=======
# Generated by Django 5.1.4 on 2025-02-20 12:33
>>>>>>> d763ff1f7562f45b0396423f2d6f887a01b25337

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ehr', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehr',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
    ]
