# Generated by Django 5.1.4 on 2025-02-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehr',
            name='patient',
            field=models.ForeignKey(default='pat', on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ehr',
            name='diagnoses',
            field=models.JSONField(blank=True, default={'diagnoses': ['art', 'necessary']}, null=True),
        ),
    ]
