# Generated by Django 5.1.4 on 2025-02-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EHR',
        ),
    ]
