# Generated by Django 5.1.4 on 2025-03-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehr',
            name='added_to_medical_history',
            field=models.BooleanField(default=False),
        ),
    ]
