# Generated by Django 5.1.4 on 2025-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehr',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
