# Generated by Django 5.1.4 on 2025-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehr',
            name='recommended_lab_test',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
