# Generated by Django 5.1.4 on 2025-02-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_alter_ehr_visit_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgeries', models.JSONField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('chronic_conditions', models.JSONField(blank=True, null=True)),
                ('injuries', models.JSONField(blank=True, null=True)),
                ('immunization_history', models.JSONField(blank=True, null=True)),
                ('allergies', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
