# Generated by Django 5.1.4 on 2025-04-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_ehr_added_to_medical_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehr',
            name='nail_image_analysis',
        ),
        migrations.RemoveField(
            model_name='ehr',
            name='test_results',
        ),
    ]
