# Generated by Django 5.1.4 on 2025-05-20 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_remove_ehr_nail_image_analysis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='family_history',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='chronic_conditions',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='immunization_history',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='injuries',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='surgeries',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='added_from_ehr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.ehr'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='episode_type',
            field=models.CharField(choices=[('Condition', 'Condition'), ('Surgery', 'Surgery'), ('Injury', 'Injury'), ('Allergy', 'Allergy'), ('Immunization', 'Immunization'), ('Other', 'Other')], default='xyz', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='title',
            field=models.CharField(default='ZYXZ', max_length=255),
            preserve_default=False,
        ),
    ]
