# Generated by Django 5.1.4 on 2025-03-27 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_patient_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtechnician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lab_technician', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
