# Generated by Django 5.1.4 on 2025-06-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_labtechnician_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='emergency_contact',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='labadmin',
            name='emergency_contact',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='labtechnician',
            name='emergency_contact',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
