# Generated by Django 3.2.25 on 2024-12-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('clinic_admin', 'Clinic Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('lab_admin', 'Lab Admin'), ('lab_technician', 'Lab Technician')], default='patient', max_length=20),
        ),
    ]
