# Generated by Django 5.1.4 on 2025-02-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctor_labadmin_labtechnician_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHR',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_allergies', models.JSONField(blank=True, null=True)),
                ('current_medications', models.JSONField(blank=True, null=True)),
                ('immunization_records', models.JSONField(blank=True, null=True)),
                ('nail_image_analysis', models.JSONField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('diagnoses', models.JSONField(blank=True, null=True)),
                ('visits', models.JSONField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
