# Generated by Django 5.1.4 on 2025-02-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ehr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EHR',
        ),
    ]
