# Generated by Django 5.1.4 on 2025-02-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_ehr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='consultation_fee',
            new_name='fee',
        ),
    ]
