# Generated by Django 5.1.4 on 2025-02-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_consultation_fee_doctor_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='fee',
        ),
    ]
