# Generated by Django 5.1.4 on 2025-02-11 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_doctor_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clinic_admin', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
