# Generated by Django 5.1.4 on 2025-04-13 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_ehr_added_to_medical_history'),
        ('model_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naildiseaseprediction',
            name='ehr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.ehr'),
        ),
    ]
