# Generated by Django 5.1.4 on 2025-03-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_role',
        ),
    ]
