# Generated by Django 5.1.4 on 2025-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_remove_feedback_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='response_text',
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
