# Generated by Django 5.1.4 on 2025-05-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_remove_feedbackresponse_response_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('Doctor Service', 'Doctor Service'), ('Appointment Issue', 'Appointment Issue'), ('Billing & Payments', 'Billing & Payments'), ('Lab Test Accuracy', 'Lab Test Accuracy'), ('Facilities & Cleanliness', 'Facilities & Cleanliness'), ('Technical Issue', 'Technical Issue'), ('Nail Report Issue', 'Nail Report Issue'), ('Suggestions and Improvements', 'Suggestions and Improvements')], max_length=50),
        ),
    ]
